In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', 999) #This option force Jupyternotebook to show all columns.

In [35]:
cols_to_use =['Date', 'Post ID', 'Network','Post Type', 'Impressions',
       'Organic Impressions', 'Engagement Rate (per Impression)',
       'Engagements', 'Reactions', 'Comments',
       'Shares','Tags']
df = pd.read_csv('Projects\Social Media Content Analysis\Post Performance_January 1, 2020 - December 31, 2020.csv', parse_dates=True, usecols=cols_to_use)

In [36]:
df.head()

,Date,Post ID,Network,Post Type,Impressions,Organic Impressions,Engagement Rate (per Impression),Engagements,Reactions,Comments,Shares,Tags
0,5/11/2020 8:53,6.67E+18,LinkedIn,Post,72,NaN,-15.30%,-11,-11,0.0,0.0,"Online Education, summer start"
1,5/11/2020 8:52,6.67E+18,LinkedIn,Post,68,NaN,-14.70%,-10,-9,0.0,-1.0,"Online Education, summer start"
2,5/29/2020 10:19,1.27E+18,Twitter,Tweet,243,NaN,0%,0,0,0.0,0.0,"FSH, Student success"
3,5/4/2020 21:56,1.26E+18,Twitter,Tweet,"1,274",NaN,0%,0,0,0.0,0.0,"FSH, Faculty, workshop"
4,4/3/2020 13:36,1.25E+18,Twitter,Tweet,852,NaN,0%,0,0,0.0,0.0,"LAN, Student success, alumni success, blog"

In [37]:
df["Tags"] = df["Tags"].replace({'Student Artwork':'Student Work','alumni success':'success','Student success':'success','faculty success':'faculty'}, regex=True)
df['Tags'] = df['Tags'].str.lower()  #format the tags data by making them lowercase
df['Tags'] = df['Tags'].str.split(pat=', ')  #split each of strings into a list

In [38]:
df.head()

,Date,Post ID,Network,Post Type,Impressions,Organic Impressions,Engagement Rate (per Impression),Engagements,Reactions,Comments,Shares,Tags
0,5/11/2020 8:53,6.67E+18,LinkedIn,Post,72,NaN,-15.30%,-11,-11,0.0,0.0,"[online education, summer start]"
1,5/11/2020 8:52,6.67E+18,LinkedIn,Post,68,NaN,-14.70%,-10,-9,0.0,-1.0,"[online education, summer start]"
2,5/29/2020 10:19,1.27E+18,Twitter,Tweet,243,NaN,0%,0,0,0.0,0.0,"[fsh, success]"
3,5/4/2020 21:56,1.26E+18,Twitter,Tweet,"1,274",NaN,0%,0,0,0.0,0.0,"[fsh, faculty, workshop]"
4,4/3/2020 13:36,1.25E+18,Twitter,Tweet,852,NaN,0%,0,0,0.0,0.0,"[lan, success, success, blog]"

In [41]:
#create a tag list
tags = df[df['Tags'].notna()]
tags = set(df['Tags'].explode().values) #Create a set to remove duplicate first
tags = list(tags) #convert the set to list
tags = [tag for tag in tags if str(tag)!= 'nan']

In [44]:
len(tags)

94

In [45]:
new_core_values = ["ideal","limitless", "inviting","outstanding","fast", "quality"]
pokemon = pd.read_csv("pokemon.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'pokemon.csv'